"""
Stage summary (D48).

Reads `.workbuddy/memory/YYYY-MM-DD.md` and produces a health summary:
  - total unique stages
  - total mentions
  - active days span
  - orphan stages (mentioned only once)
  - health grade (A/B/C/D) based on coverage
"""

from __future__ import annotations

import argparse
import json
import re
import time
from collections import Counter
from dataclasses import asdict, dataclass
from datetime import date
from pathlib import Path
from typing import Optional


_STAGE_ID_RE = re.compile(r"\bD(\d+)\b")
_ISO_DATE_RE = re.compile(r"^(\d{4})-(\d{2})-(\d{2})\.md$")


def _safe_read(path: Path) -> str:
    if not path.exists():
        return ""
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return ""


def _parse_date(p: Path) -> Optional[date]:
    m = _ISO_DATE_RE.match(p.name)
    if not m:
        return None
    try:
        return date(int(m.group(1)), int(m.group(2)),
                    int(m.group(3)))
    except ValueError:
        return None


def _stages_in(text: str) -> list[str]:
    out: list[str] = []
    for line in text.splitlines():
        if line.startswith("##") and not line.startswith("###"):
            for sid in _STAGE_ID_RE.findall(line):
                out.append(f"D{sid}")
    return out


@dataclass
class SummaryReport:
    n_stages: int
    n_total_mentions: int
    n_active_days: int
    n_orphans: int
    health: str
    health_score: int

    def to_dict(self) -> dict:
        return {
            "n_stages": self.n_stages,
            "n_total_mentions": self.n_total_mentions,
            "n_active_days": self.n_active_days,
            "n_orphans": self.n_orphans,
            "health": self.health,
            "health_score": self.health_score,
        }


def build_summary(memory_dir: Path) -> SummaryReport:
    if not memory_dir.is_dir():
        return SummaryReport(0, 0, 0, 0, "D", 0)
    mentions: Counter = Counter()
    active_days: set = set()
    for p in memory_dir.glob("*.md"):
        d = _parse_date(p)
        if d is None:
            continue
        active_days.add(d)
        for s in _stages_in(_safe_read(p)):
            mentions[s] += 1
    n_stages = len(mentions)
    n_mentions = sum(mentions.values())
    n_active = len(active_days)
    n_orphans = sum(1 for c in mentions.values() if c == 1)
    # Health score 0-100
    score = 0
    if n_stages > 0:
        # Coverage: 1 - orphan ratio
        score += int(100 * (1 - n_orphans / n_stages))
    if n_active > 0:
        score = min(100, score)
    # Grade
    if score >= 80:
        grade = "A"
    elif score >= 60:
        grade = "B"
    elif score >= 40:
        grade = "C"
    else:
        grade = "D"
    return SummaryReport(
        n_stages=n_stages,
        n_total_mentions=n_mentions,
        n_active_days=n_active,
        n_orphans=n_orphans,
        health=grade,
        health_score=score,
    )


def render_markdown(report: SummaryReport) -> str:
    out: list[str] = ["# Stage Summary", ""]
    out.append(f"*Generated by `src.analysis.stage_summary` on "
                f"{time.strftime('%Y-%m-%d %H:%M:%S')}*\n")
    if report.n_stages == 0:
        out.append("*(no data)*\n")
        return "\n".join(out)
    out.append("## Health\n")
    out.append(f"- **Grade**: {report.health} "
                f"({report.health_score}/100)")
    out.append("")
    out.append("## Summary\n")
    out.append(f"- **Unique stages**: {report.n_stages}")
    out.append(f"- **Total mentions**: {report.n_total_mentions}")
    out.append(f"- **Active days**: {report.n_active_days}")
    out.append(f"- **Orphan stages (1 mention only)**: "
                f"{report.n_orphans}")
    out.append("")
    return "\n".join(out)


def render_json(report: SummaryReport) -> dict:
    return {"report": report.to_dict()}


def main() -> int:
    p = argparse.ArgumentParser(description="Stage summary health")
    p.add_argument("--memory_dir", type=Path,
                   default=Path("../.workbuddy/memory"))
    p.add_argument("--out", type=Path,
                   default=Path("report/stage_summary.md"))
    p.add_argument("--out_json", type=Path,
                   default=Path("report/stage_summary.json"))
    args = p.parse_args()
    report = build_summary(args.memory_dir)
    md = render_markdown(report)
    print(f"[summary] {report.n_stages} stages; "
          f"health={report.health} ({report.health_score})")
    print(md)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(md, encoding="utf-8")
    print(f"Wrote Markdown -> {args.out}")
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(
        json.dumps(render_json(report), indent=2, ensure_ascii=False),
        encoding="utf-8")
    print(f"Wrote JSON     -> {args.out_json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
