"""
Stage velocity (D55).

Reads `.workbuddy/memory/YYYY-MM-DD.md` and computes stage velocity
- how many active epochs each stage has, plus the mean epoch length
(in days). An "epoch" is a maximal run of consecutive days in which
the stage is mentioned.
"""

from __future__ import annotations

import argparse
import json
import re
import time
from collections import defaultdict
from dataclasses import asdict, dataclass
from datetime import date
from pathlib import Path
from typing import Optional


_STAGE_ID_RE = re.compile(r"\bD(\d+)\b")
_ISO_DATE_RE = re.compile(r"^(\d{4})-(\d{2})-(\d{2})\.md$")


def _safe_read(path: Path) -> str:
    if not path.exists():
        return ""
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return ""


def _parse_date(p: Path) -> Optional[date]:
    m = _ISO_DATE_RE.match(p.name)
    if not m:
        return None
    try:
        return date(int(m.group(1)), int(m.group(2)),
                    int(m.group(3)))
    except ValueError:
        return None


def _stages_in(text: str) -> list[str]:
    out: list[str] = []
    for line in text.splitlines():
        if line.startswith("##") and not line.startswith("###"):
            for sid in _STAGE_ID_RE.findall(line):
                out.append(f"D{sid}")
    return out


@dataclass
class VelocityEntry:
    id: str
    n_days: int
    n_epochs: int
    mean_epoch_days: float
    max_epoch_days: int
    total_days_active: int
    active_ratio: float
    first_date: str
    last_date: str

    def to_row(self) -> tuple:
        return (self.id, str(self.n_days),
                str(self.n_epochs),
                f"{self.mean_epoch_days:.2f}",
                str(self.max_epoch_days),
                f"{self.active_ratio:.2f}",
                self.first_date, self.last_date)


def _epochs(dates: list) -> list:
    if not dates:
        return []
    sorted_d = sorted(dates)
    epochs: list = [[sorted_d[0]]]
    for d in sorted_d[1:]:
        if (d - epochs[-1][-1]).days == 1:
            epochs[-1].append(d)
        else:
            epochs.append([d])
    return epochs


def collect_velocity(memory_dir: Path) -> list:
    if not memory_dir.is_dir():
        return []
    stage_to_dates: dict = defaultdict(set)
    for p in memory_dir.glob("*.md"):
        d = _parse_date(p)
        if d is None:
            continue
        for s in _stages_in(_safe_read(p)):
            stage_to_dates[s].add(d)
    if not stage_to_dates:
        return []
    all_active_days = sorted({d for ds in stage_to_dates.values()
                                for d in ds})
    n_total_active = len(all_active_days)
    out: list = []
    for stage in sorted(stage_to_dates.keys()):
        dates = sorted(stage_to_dates[stage])
        eps = _epochs(dates)
        n_epochs = len(eps)
        epoch_lengths = [len(e) for e in eps]
        total_days = sum(epoch_lengths)
        mean_epoch = (sum(epoch_lengths) / n_epochs) if n_epochs else 0.0
        max_epoch = max(epoch_lengths) if epoch_lengths else 0
        active_ratio = total_days / n_total_active if n_total_active else 0.0
        out.append(VelocityEntry(
            id=stage,
            n_days=len(dates),
            n_epochs=n_epochs,
            mean_epoch_days=mean_epoch,
            max_epoch_days=max_epoch,
            total_days_active=total_days,
            active_ratio=active_ratio,
            first_date=dates[0].isoformat() if dates else "",
            last_date=dates[-1].isoformat() if dates else "",
        ))
    out.sort(key=lambda v: (-v.n_epochs, -v.mean_epoch_days, v.id))
    return out


def render_markdown(entries: list) -> str:
    out: list[str] = ["# Stage Velocity", ""]
    out.append(f"*Generated by `src.analysis.stage_velocity` on "
                f"{time.strftime('%Y-%m-%d %H:%M:%S')}*\n")
    if not entries:
        out.append("*(no data)*\n")
        return "\n".join(out)
    n_total = len(entries)
    n_1_epoch = sum(1 for e in entries if e.n_epochs == 1)
    multi = n_total - n_1_epoch
    out.append("## Summary\n")
    out.append(f"- **Stages**: {n_total}")
    out.append(f"- **Single-epoch (one burst)**: {n_1_epoch}")
    out.append(f"- **Multi-epoch (intermittent)**: {multi}")
    if entries:
        max_n = max(e.n_epochs for e in entries)
        out.append(f"- **Max epochs observed**: {max_n}")
    out.append("")
    out.append("## Per-stage velocity (sorted by n_epochs desc)\n")
    out.append("| id | days | epochs | mean_ep | max_ep | active_ratio | first | last |")
    out.append("|---|---|---|---|---|---|---|---|")
    for e in entries:
        out.append("| " + " | ".join(e.to_row()) + " |")
    out.append("")
    top = sorted(entries, key=lambda e: -e.total_days_active)[:10]
    out.append("## Top 10 most-active stages (by total days active)\n")
    out.append("| id | total_days | n_epochs | mean_ep |")
    out.append("|---|---|---|---|")
    for e in top:
        out.append(f"| {e.id} | {e.total_days_active} | "
                    f"{e.n_epochs} | {e.mean_epoch_days:.2f} |")
    out.append("")
    return "\n".join(out)


def render_json(entries: list) -> dict:
    return {
        "n_stages": len(entries),
        "entries": [asdict(e) for e in entries],
    }


def main() -> int:
    p = argparse.ArgumentParser(
        description="Stage velocity (epochs + active ratio)")
    p.add_argument("--memory_dir", type=Path,
                   default=Path("../.workbuddy/memory"))
    p.add_argument("--out", type=Path,
                   default=Path("report/stage_velocity.md"))
    p.add_argument("--out_json", type=Path,
                   default=Path("report/stage_velocity.json"))
    args = p.parse_args()
    entries = collect_velocity(args.memory_dir)
    md = render_markdown(entries)
    print(f"[velocity] {len(entries)} stages; "
          f"max_epochs={max((e.n_epochs for e in entries), default=0)}")
    print(md)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(md, encoding="utf-8")
    print(f"Wrote Markdown -> {args.out}")
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(
        json.dumps(render_json(entries), indent=2, ensure_ascii=False),
        encoding="utf-8")
    print(f"Wrote JSON     -> {args.out_json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
