"""
Stage leaderboard (D42).

Reads `.workbuddy/memory/YYYY-MM-DD.md` and produces a leaderboard
of stage IDs by mention frequency, with recency classification
(one-shot, repeat, this-week-only).
"""

from __future__ import annotations

import argparse
import json
import re
import time
from collections import Counter
from dataclasses import asdict, dataclass
from datetime import date, timedelta
from pathlib import Path
from typing import Optional


_STAGE_ID_RE = re.compile(r"\bD(\d+)\b")
_ISO_DATE_RE = re.compile(r"^(\d{4})-(\d{2})-(\d{2})\.md$")


def _safe_read(path: Path) -> str:
    if not path.exists():
        return ""
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return ""


def _parse_date(p: Path) -> Optional[date]:
    m = _ISO_DATE_RE.match(p.name)
    if not m:
        return None
    try:
        return date(int(m.group(1)), int(m.group(2)),
                    int(m.group(3)))
    except ValueError:
        return None


def _stages_in(text: str) -> list[str]:
    out: list[str] = []
    for line in text.splitlines():
        if line.startswith("##") and not line.startswith("###"):
            for sid in _STAGE_ID_RE.findall(line):
                out.append(f"D{sid}")
    return out


def _normalize_did(s: str) -> str:
    m = re.match(r"^D(\d+)$", s)
    if not m:
        return s
    n = int(m.group(1))
    return f"D{n:02d}" if n < 10 else f"D{n}"


@dataclass
class LeaderboardReport:
    n_unique_stages: int
    n_total_mentions: int
    n_one_shot: int
    n_repeat: int
    n_this_week: int
    top_20: list  # (id, count, last_seen, classification)

    def to_dict(self) -> dict:
        return {
            "n_unique_stages": self.n_unique_stages,
            "n_total_mentions": self.n_total_mentions,
            "n_one_shot": self.n_one_shot,
            "n_repeat": self.n_repeat,
            "n_this_week": self.n_this_week,
            "top_20": [list(t) for t in self.top_20],
        }


def build_leaderboard(memory_dir: Path,
                        today: Optional[date] = None) -> LeaderboardReport:
    if today is None:
        today = date.today()
    if not memory_dir.is_dir():
        return LeaderboardReport(0, 0, 0, 0, 0, [])
    counts: Counter = Counter()
    last_seen: dict = {}
    for p in memory_dir.glob("*.md"):
        d = _parse_date(p)
        if d is None:
            continue
        for s in _stages_in(_safe_read(p)):
            ns = _normalize_did(s)
            counts[ns] += 1
            if ns not in last_seen or d > last_seen[ns]:
                last_seen[ns] = d
    week_start = today - timedelta(days=today.weekday())
    one_shot = sum(1 for c in counts.values() if c == 1)
    repeat = sum(1 for c in counts.values() if c >= 2)
    this_week = sum(1 for s, d in last_seen.items()
                     if d >= week_start)
    top = counts.most_common(20)
    top_data = []
    for s, c in top:
        d = last_seen.get(s)
        if c == 1:
            klass = "one-shot"
        elif d and d >= week_start:
            klass = "this-week"
        else:
            klass = "repeat"
        top_data.append((s, c, d.isoformat() if d else "",
                          klass))
    return LeaderboardReport(
        n_unique_stages=len(counts),
        n_total_mentions=sum(counts.values()),
        n_one_shot=one_shot,
        n_repeat=repeat,
        n_this_week=this_week,
        top_20=top_data,
    )


def render_markdown(report: LeaderboardReport) -> str:
    lines: list = ["# Stage Leaderboard", ""]
    lines.append(f"*Generated by `src.analysis.stage_leaderboard` on "
                  f"{time.strftime('%Y-%m-%d %H:%M:%S')}*\n")
    if report.n_unique_stages == 0:
        lines.append("*(no data)*\n")
        return "\n".join(lines)
    lines.append("## Summary\n")
    lines.append(f"- **Unique stages**: {report.n_unique_stages}")
    lines.append(f"- **Total mentions**: {report.n_total_mentions}")
    lines.append(f"- **One-shot (1 mention)**: {report.n_one_shot}")
    lines.append(f"- **Repeat (>=2 mentions)**: {report.n_repeat}")
    lines.append(f"- **This week**: {report.n_this_week}")
    lines.append("")
    lines.append("## Top 20 stages\n")
    lines.append("| id | mentions | last_seen | class |")
    lines.append("|---|---|---|---|")
    for sid, c, d, k in report.top_20:
        lines.append(f"| {sid} | {c} | {d} | {k} |")
    lines.append("")
    return "\n".join(lines)


def render_json(report: LeaderboardReport) -> dict:
    return {"report": report.to_dict()}


def main() -> int:
    p = argparse.ArgumentParser(description="Stage leaderboard")
    p.add_argument("--memory_dir", type=Path,
                   default=Path("../.workbuddy/memory"))
    p.add_argument("--out", type=Path,
                   default=Path("report/stage_leaderboard.md"))
    p.add_argument("--out_json", type=Path,
                   default=Path("report/stage_leaderboard.json"))
    args = p.parse_args()
    report = build_leaderboard(args.memory_dir)
    md = render_markdown(report)
    print(f"[leaderboard] {report.n_unique_stages} unique; "
          f"{report.n_one_shot} one-shot; "
          f"{report.n_repeat} repeat; "
          f"{report.n_this_week} this-week")
    print(md)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(md, encoding="utf-8")
    print(f"Wrote Markdown -> {args.out}")
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(
        json.dumps(render_json(report), indent=2, ensure_ascii=False),
        encoding="utf-8")
    print(f"Wrote JSON     -> {args.out_json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
