"""
Stage distribution (D57).

Reads `.workbuddy/memory/YYYY-MM-DD.md` and computes the
distribution of stage mention counts: how many stages were
mentioned 1x / 2x / 3x / 4x / 5+x in the entire memory log.

Provides:
  - mention_count buckets (1, 2, 3, 4, 5+)
  - total / unique stages / mean / median / Gini
  - top 10 most-mentioned stages
"""

from __future__ import annotations

import argparse
import json
import re
import time
from collections import Counter
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Optional


_STAGE_ID_RE = re.compile(r"\bD(\d+)\b")
_ISO_DATE_RE = re.compile(r"^(\d{4})-(\d{2})-(\d{2})\.md$")


def _safe_read(path: Path) -> str:
    if not path.exists():
        return ""
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return ""


def _parse_date(p: Path) -> Optional[object]:
    from datetime import date
    m = _ISO_DATE_RE.match(p.name)
    if not m:
        return None
    try:
        return date(int(m.group(1)), int(m.group(2)),
                    int(m.group(3)))
    except ValueError:
        return None


def _stages_in(text: str) -> list[str]:
    out: list[str] = []
    for line in text.splitlines():
        if line.startswith("##") and not line.startswith("###"):
            for sid in _STAGE_ID_RE.findall(line):
                out.append(f"D{sid}")
    return out


@dataclass
class DistributionReport:
    n_stages: int
    n_total_mentions: int
    mean_mentions: float
    median_mentions: float
    gini: float
    buckets: dict
    top_10: list

    def to_dict(self) -> dict:
        return {
            "n_stages": self.n_stages,
            "n_total_mentions": self.n_total_mentions,
            "mean_mentions": self.mean_mentions,
            "median_mentions": self.median_mentions,
            "gini": self.gini,
            "buckets": self.buckets,
            "top_10": [list(p) for p in self.top_10],
        }


def collect_mentions(memory_dir: Path) -> Counter:
    if not memory_dir.is_dir():
        return Counter()
    mentions: Counter = Counter()
    for p in memory_dir.glob("*.md"):
        for s in _stages_in(_safe_read(p)):
            mentions[s] += 1
    return mentions


def _gini(counts: list) -> float:
    if not counts or sum(counts) == 0:
        return 0.0
    s = sorted(counts)
    n = len(s)
    cum = sum((i + 1) * v for i, v in enumerate(s))
    return (2 * cum) / (n * sum(s)) - (n + 1) / n


def _median(xs: list) -> float:
    if not xs:
        return 0.0
    s = sorted(xs)
    n = len(s)
    if n % 2 == 1:
        return float(s[n // 2])
    return (s[n // 2 - 1] + s[n // 2]) / 2.0


def build_distribution(mentions: Counter) -> DistributionReport:
    if not mentions:
        return DistributionReport(0, 0, 0.0, 0.0, 0.0,
                                    {"1": 0, "2": 0, "3": 0, "4": 0, "5+": 0},
                                    [])
    counts = list(mentions.values())
    total = sum(counts)
    n = len(counts)
    buckets: dict = {"1": 0, "2": 0, "3": 0, "4": 0, "5+": 0}
    for c in counts:
        if c >= 5:
            buckets["5+"] += 1
        else:
            buckets[str(c)] += 1
    return DistributionReport(
        n_stages=n,
        n_total_mentions=total,
        mean_mentions=total / n,
        median_mentions=_median([float(c) for c in counts]),
        gini=_gini(counts),
        buckets=buckets,
        top_10=mentions.most_common(10),
    )


def render_markdown(report: DistributionReport) -> str:
    out: list[str] = ["# Stage Distribution", ""]
    out.append(f"*Generated by `src.analysis.stage_distribution` on "
                f"{time.strftime('%Y-%m-%d %H:%M:%S')}*\n")
    if report.n_stages == 0:
        out.append("*(no data)*\n")
        return "\n".join(out)
    out.append("## Summary\n")
    out.append(f"- **Total unique stages**: {report.n_stages}")
    out.append(f"- **Total mentions**: {report.n_total_mentions}")
    out.append(f"- **Mean mentions per stage**: "
                f"{report.mean_mentions:.2f}")
    out.append(f"- **Median mentions per stage**: "
                f"{report.median_mentions:.1f}")
    out.append(f"- **Gini coefficient**: {report.gini:.3f} "
                f"(0=equal, 1=concentrated)")
    out.append("")
    out.append("## Mention-count buckets\n")
    out.append("| bucket | n_stages | share |")
    out.append("|---|---|---|")
    for label, cnt in report.buckets.items():
        share = cnt / report.n_stages if report.n_stages else 0.0
        out.append(f"| {label} | {cnt} | {share:.1%} |")
    out.append("")
    if report.top_10:
        out.append("## Top 10 most-mentioned stages\n")
        out.append("| stage | mentions |")
        out.append("|---|---|")
        for s, c in report.top_10:
            out.append(f"| {s} | {c} |")
        out.append("")
    return "\n".join(out)


def render_json(report: DistributionReport) -> dict:
    return {"report": report.to_dict()}


def main() -> int:
    p = argparse.ArgumentParser(
        description="Stage distribution (mention histogram + Gini)")
    p.add_argument("--memory_dir", type=Path,
                   default=Path("../.workbuddy/memory"))
    p.add_argument("--out", type=Path,
                   default=Path("report/stage_distribution.md"))
    p.add_argument("--out_json", type=Path,
                   default=Path("report/stage_distribution.json"))
    args = p.parse_args()
    mentions = collect_mentions(args.memory_dir)
    report = build_distribution(mentions)
    md = render_markdown(report)
    print(f"[distribution] {report.n_stages} stages; "
          f"{report.n_total_mentions} mentions; "
          f"mean={report.mean_mentions:.2f}; "
          f"gini={report.gini:.3f}")
    print(md)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(md, encoding="utf-8")
    print(f"Wrote Markdown -> {args.out}")
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(
        json.dumps(render_json(report), indent=2, ensure_ascii=False),
        encoding="utf-8")
    print(f"Wrote JSON     -> {args.out_json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
