"""
Stage timeline (D45).

Reads `.workbuddy/memory/YYYY-MM-DD.md` and computes the first-seen
date for each stage ID, plus gaps and span statistics.
"""

from __future__ import annotations

import argparse
import json
import re
import time
from collections import defaultdict
from dataclasses import asdict, dataclass
from datetime import date, timedelta
from pathlib import Path
from typing import Optional


_STAGE_ID_RE = re.compile(r"\bD(\d+)\b")
_ISO_DATE_RE = re.compile(r"^(\d{4})-(\d{2})-(\d{2})\.md$")


def _safe_read(path: Path) -> str:
    if not path.exists():
        return ""
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return ""


def _parse_date(p: Path) -> Optional[date]:
    m = _ISO_DATE_RE.match(p.name)
    if not m:
        return None
    try:
        return date(int(m.group(1)), int(m.group(2)),
                    int(m.group(3)))
    except ValueError:
        return None


def _stages_in(text: str) -> list[str]:
    out: list[str] = []
    for line in text.splitlines():
        if line.startswith("##") and not line.startswith("###"):
            for sid in _STAGE_ID_RE.findall(line):
                out.append(f"D{sid}")
    return out


def _normalize_did(s: str) -> str:
    m = re.match(r"^D(\d+)$", s)
    if not m:
        return s
    n = int(m.group(1))
    return f"D{n:02d}" if n < 10 else f"D{n}"


def _median(xs: list) -> float:
    if not xs:
        return 0.0
    s = sorted(xs)
    n = len(s)
    if n % 2 == 1:
        return float(s[n // 2])
    return (s[n // 2 - 1] + s[n // 2]) / 2.0


@dataclass
class TimelineReport:
    n_stages: int
    span_days: int
    median_gap_days: float
    first_seen: dict
    last_seen: dict

    def to_dict(self) -> dict:
        return {
            "n_stages": self.n_stages,
            "span_days": self.span_days,
            "median_gap_days": self.median_gap_days,
            "first_seen": self.first_seen,
            "last_seen": self.last_seen,
        }


def build_timeline(memory_dir: Path) -> TimelineReport:
    if not memory_dir.is_dir():
        return TimelineReport(0, 0, 0.0, {}, {})
    first_seen: dict = {}
    last_seen: dict = {}
    for p in memory_dir.glob("*.md"):
        d = _parse_date(p)
        if d is None:
            continue
        for s in _stages_in(_safe_read(p)):
            ns = _normalize_did(s)
            if ns not in first_seen or d < first_seen[ns]:
                first_seen[ns] = d
            if ns not in last_seen or d > last_seen[ns]:
                last_seen[ns] = d
    if not first_seen:
        return TimelineReport(0, 0, 0.0, {}, {})
    sorted_stages = sorted(first_seen.items(), key=lambda x: x[1])
    first_date = sorted_stages[0][1]
    last_date = max(last_seen.values())
    span = (last_date - first_date).days
    gaps = []
    for i in range(1, len(sorted_stages)):
        d_prev = sorted_stages[i - 1][1]
        d_cur = sorted_stages[i][1]
        gaps.append((d_cur - d_prev).days)
    median_gap = _median([float(g) for g in gaps]) if gaps else 0.0
    return TimelineReport(
        n_stages=len(first_seen),
        span_days=span,
        median_gap_days=median_gap,
        first_seen={s: d.isoformat() for s, d in first_seen.items()},
        last_seen={s: d.isoformat() for s, d in last_seen.items()},
    )


def render_markdown(report: TimelineReport) -> str:
    out: list[str] = ["# Stage Timeline", ""]
    out.append(f"*Generated by `src.analysis.stage_timeline` on "
                f"{time.strftime('%Y-%m-%d %H:%M:%S')}*\n")
    if report.n_stages == 0:
        out.append("*(no data)*\n")
        return "\n".join(out)
    out.append("## Summary\n")
    out.append(f"- **Stages**: {report.n_stages}")
    out.append(f"- **Span (first to last first-seen)**: "
                f"{report.span_days} days")
    out.append(f"- **Median gap between new stages**: "
                f"{report.median_gap_days:.1f} days")
    out.append("")
    out.append("## First-seen (top 20 by id)\n")
    out.append("| stage | first_seen | last_seen |")
    out.append("|---|---|---|")
    for sid in sorted(report.first_seen.keys())[:20]:
        out.append(f"| {sid} | {report.first_seen[sid]} | "
                    f"{report.last_seen.get(sid, '')} |")
    out.append("")
    return "\n".join(out)


def render_json(report: TimelineReport) -> dict:
    return {"report": report.to_dict()}


def main() -> int:
    p = argparse.ArgumentParser(
        description="Stage timeline (first-seen dates + gaps)")
    p.add_argument("--memory_dir", type=Path,
                   default=Path("../.workbuddy/memory"))
    p.add_argument("--out", type=Path,
                   default=Path("report/stage_timeline.md"))
    p.add_argument("--out_json", type=Path,
                   default=Path("report/stage_timeline.json"))
    args = p.parse_args()
    report = build_timeline(args.memory_dir)
    md = render_markdown(report)
    print(f"[timeline] {report.n_stages} stages; "
          f"span={report.span_days}d; "
          f"median_gap={report.median_gap_days:.1f}d")
    print(md)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(md, encoding="utf-8")
    print(f"Wrote Markdown -> {args.out}")
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(
        json.dumps(render_json(report), indent=2, ensure_ascii=False),
        encoding="utf-8")
    print(f"Wrote JSON     -> {args.out_json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
