"""
Stage fanout (D50).

Reads `.workbuddy/memory/YYYY-MM-DD.md` and computes stage co-occurrence:
for each pair (Dxx, Dyy), how many files mention both. Reports Jaccard
similarity and overall graph density.
"""

from __future__ import annotations

import argparse
import json
import re
import time
from collections import defaultdict
from dataclasses import asdict, dataclass
from itertools import combinations
from pathlib import Path
from typing import Optional


_STAGE_ID_RE = re.compile(r"\bD(\d+)\b")
_ISO_DATE_RE = re.compile(r"^(\d{4})-(\d{2})-(\d{2})\.md$")


def _safe_read(path: Path) -> str:
    if not path.exists():
        return ""
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return ""


def _parse_date(p: Path) -> Optional[object]:
    from datetime import date
    m = _ISO_DATE_RE.match(p.name)
    if not m:
        return None
    try:
        return date(int(m.group(1)), int(m.group(2)),
                    int(m.group(3)))
    except ValueError:
        return None


def _stages_in(text: str) -> list[str]:
    out: list[str] = []
    for line in text.splitlines():
        if line.startswith("##") and not line.startswith("###"):
            for sid in _STAGE_ID_RE.findall(line):
                out.append(f"D{sid}")
    return out


def collect_file_stages(memory_dir: Path) -> list:
    if not memory_dir.is_dir():
        return []
    out: list = []
    for p in memory_dir.glob("*.md"):
        stages = _stages_in(_safe_read(p))
        if stages:
            out.append(sorted(set(stages)))
    return out


def build_pair_counts(file_stages: list) -> dict:
    pair_counts: dict = defaultdict(int)
    for stages in file_stages:
        for a, b in combinations(stages, 2):
            pair_counts[frozenset({a, b})] += 1
    return pair_counts


def jaccard(a: str, b: str, pair_counts: dict) -> float:
    pair_ab = pair_counts.get(frozenset({a, b}), 0)
    if pair_ab == 0:
        return 0.0
    pair_a = sum(c for p, c in pair_counts.items() if a in p)
    pair_b = sum(c for p, c in pair_counts.items() if b in p)
    union = pair_a + pair_b - pair_ab
    return pair_ab / union if union else 0.0


@dataclass
class FanoutReport:
    n_files: int
    n_stages: int
    n_pairs: int
    n_total: int
    density: float
    top_pairs: list

    def to_dict(self) -> dict:
        return {
            "n_files": self.n_files,
            "n_stages": self.n_stages,
            "n_pairs": self.n_pairs,
            "n_total": self.n_total,
            "density": self.density,
            "top_pairs": [list(p) for p in self.top_pairs],
        }


def build_fanout(memory_dir: Path) -> FanoutReport:
    file_stages = collect_file_stages(memory_dir)
    all_stages = {s for fs in file_stages for s in fs}
    pair_counts = build_pair_counts(file_stages)
    n_total = sum(pair_counts.values())
    n_pairs = len(pair_counts)
    density = n_total / n_pairs if n_pairs else 0.0
    sorted_pairs = sorted(pair_counts.items(), key=lambda x: -x[1])
    top_pairs = [(list(p), c) for p, c in sorted_pairs[:20]]
    return FanoutReport(
        n_files=len(file_stages),
        n_stages=len(all_stages),
        n_pairs=n_pairs,
        n_total=n_total,
        density=density,
        top_pairs=top_pairs,
    )


def render_markdown(report: FanoutReport) -> str:
    out: list[str] = ["# Stage Fanout", ""]
    out.append(f"*Generated by `src.analysis.stage_fanout` on "
                f"{time.strftime('%Y-%m-%d %H:%M:%S')}*\n")
    if report.n_files == 0:
        out.append("*(no data)*\n")
        return "\n".join(out)
    out.append("## Summary\n")
    out.append(f"- **Files scanned**: {report.n_files}")
    out.append(f"- **Unique stages**: {report.n_stages}")
    out.append(f"- **Pairs**: {report.n_pairs}")
    out.append(f"- **Total edge weight**: {report.n_total}")
    out.append(f"- **Average co-occurrence per pair**: "
                f"{report.density:.2f}")
    out.append("")
    out.append("## Top 20 co-occurring pairs\n")
    out.append("| pair | count |")
    out.append("|---|---|")
    for pair, c in report.top_pairs:
        out.append(f"| {pair[0]} <-> {pair[1]} | {c} |")
    out.append("")
    return "\n".join(out)


def render_json(report: FanoutReport) -> dict:
    return {"report": report.to_dict()}


def main() -> int:
    p = argparse.ArgumentParser(
        description="Stage fanout (co-occurrence pairs + Jaccard + density)")
    p.add_argument("--memory_dir", type=Path,
                   default=Path("../.workbuddy/memory"))
    p.add_argument("--out", type=Path,
                   default=Path("report/stage_fanout.md"))
    p.add_argument("--out_json", type=Path,
                   default=Path("report/stage_fanout.json"))
    args = p.parse_args()
    report = build_fanout(args.memory_dir)
    md = render_markdown(report)
    print(f"[fanout] {report.n_files} files, "
          f"{report.n_stages} stages, "
          f"{report.n_pairs} pairs, "
          f"density={report.density:.2f}")
    print(md)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(md, encoding="utf-8")
    print(f"Wrote Markdown -> {args.out}")
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(
        json.dumps(render_json(report), indent=2, ensure_ascii=False),
        encoding="utf-8")
    print(f"Wrote JSON     -> {args.out_json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
