"""
Stage trend (D49).

Reads `.workbuddy/memory/YYYY-MM-DD.md` and produces a week-over-week
trend of stage mentions: which weeks have how many new stage IDs
appear, and what the projection for next week is.
"""

from __future__ import annotations

import argparse
import json
import re
import time
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass
from datetime import date, timedelta
from pathlib import Path
from typing import Optional


_STAGE_ID_RE = re.compile(r"\bD(\d+)\b")
_ISO_DATE_RE = re.compile(r"^(\d{4})-(\d{2})-(\d{2})\.md$")


def _safe_read(path: Path) -> str:
    if not path.exists():
        return ""
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return ""


def _parse_date(p: Path) -> Optional[date]:
    m = _ISO_DATE_RE.match(p.name)
    if not m:
        return None
    try:
        return date(int(m.group(1)), int(m.group(2)),
                    int(m.group(3)))
    except ValueError:
        return None


def _stages_in(text: str) -> list[str]:
    out: list[str] = []
    for line in text.splitlines():
        if line.startswith("##") and not line.startswith("###"):
            for sid in _STAGE_ID_RE.findall(line):
                out.append(f"D{sid}")
    return out


def _week_of(d: date) -> str:
    y, w, _ = d.isocalendar()
    return f"{y}-W{w:02d}"


def collect_weekly(memory_dir: Path) -> tuple:
    if not memory_dir.is_dir():
        return {}, set()
    per_week_first_seen: dict = defaultdict(set)
    for p in memory_dir.glob("*.md"):
        d = _parse_date(p)
        if d is None:
            continue
        w = _week_of(d)
        for s in _stages_in(_safe_read(p)):
            per_week_first_seen[w].add(s)
    all_stages: set = set()
    for stages in per_week_first_seen.values():
        all_stages |= stages
    return per_week_first_seen, all_stages


def _linear_projection(weeks: list) -> int:
    """Simple linear regression on (idx, count) -> next-week prediction."""
    if len(weeks) < 2:
        return weeks[-1][1] if weeks else 0
    n = len(weeks)
    xs = list(range(n))
    ys = [c for _, c in weeks]
    mean_x = sum(xs) / n
    mean_y = sum(ys) / n
    num = sum((x - mean_x) * (y - mean_y) for x, y in zip(xs, ys))
    den = sum((x - mean_x) ** 2 for x in xs)
    if den == 0:
        return int(round(mean_y))
    slope = num / den
    intercept = mean_y - slope * mean_x
    next_val = intercept + slope * n
    return max(0, int(round(next_val)))


@dataclass
class TrendReport:
    n_weeks: int
    n_first_seen_total: int
    n_unique_stages: int
    direction: str  # "up" / "down" / "flat"
    next_week_projection: int
    weekly: list

    def to_dict(self) -> dict:
        return {
            "n_weeks": self.n_weeks,
            "n_first_seen_total": self.n_first_seen_total,
            "n_unique_stages": self.n_unique_stages,
            "direction": self.direction,
            "next_week_projection": self.next_week_projection,
            "weekly": [list(w) for w in self.weekly],
        }


def build_trend(memory_dir: Path) -> TrendReport:
    per_week, all_stages = collect_weekly(memory_dir)
    if not per_week:
        return TrendReport(0, 0, 0, "flat", 0, [])
    weekly = sorted((w, len(s)) for w, s in per_week.items())
    n_total = sum(c for _, c in weekly)
    direction = "flat"
    if len(weekly) >= 2:
        last = weekly[-1][1]
        prev = weekly[-2][1]
        if last > prev:
            direction = "up"
        elif last < prev:
            direction = "down"
    proj = _linear_projection(weekly)
    return TrendReport(
        n_weeks=len(weekly),
        n_first_seen_total=n_total,
        n_unique_stages=len(all_stages),
        direction=direction,
        next_week_projection=proj,
        weekly=weekly,
    )


def render_markdown(report: TrendReport) -> str:
    out: list[str] = ["# Stage Trend", ""]
    out.append(f"*Generated by `src.analysis.stage_trend` on "
                f"{time.strftime('%Y-%m-%d %H:%M:%S')}*\n")
    if report.n_weeks == 0:
        out.append("*(no data)*\n")
        return "\n".join(out)
    out.append("## Summary\n")
    out.append(f"- **Weeks observed**: {report.n_weeks}")
    out.append(f"- **Total first-seen**: {report.n_first_seen_total}")
    out.append(f"- **Unique stages**: {report.n_unique_stages}")
    out.append(f"- **Direction (last vs prev)**: {report.direction}")
    out.append(f"- **Next-week projection (linear)**: "
                f"{report.next_week_projection}")
    out.append("")
    out.append("## Per-week new stages\n")
    out.append("| week | new_stages |")
    out.append("|---|---|")
    for w, c in report.weekly:
        out.append(f"| {w} | {c} |")
    out.append("")
    return "\n".join(out)


def render_json(report: TrendReport) -> dict:
    return {"report": report.to_dict()}


def main() -> int:
    p = argparse.ArgumentParser(
        description="Stage trend (week-over-week new stages)")
    p.add_argument("--memory_dir", type=Path,
                   default=Path("../.workbuddy/memory"))
    p.add_argument("--out", type=Path,
                   default=Path("report/stage_trend.md"))
    p.add_argument("--out_json", type=Path,
                   default=Path("report/stage_trend.json"))
    args = p.parse_args()
    report = build_trend(args.memory_dir)
    md = render_markdown(report)
    print(f"[trend] {report.n_weeks} weeks; "
          f"direction={report.direction}; "
          f"next={report.next_week_projection}")
    print(md)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(md, encoding="utf-8")
    print(f"Wrote Markdown -> {args.out}")
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(
        json.dumps(render_json(report), indent=2, ensure_ascii=False),
        encoding="utf-8")
    print(f"Wrote JSON     -> {args.out_json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
