"""
Stage streak (D41).

Reads `.workbuddy/memory/YYYY-MM-DD.md` and computes:
  - per-day count of distinct stages mentioned
  - streak: longest consecutive run of active days
  - current streak (ending today)
  - first-seen dates
"""

from __future__ import annotations

import argparse
import json
import re
import time
from collections import defaultdict
from dataclasses import asdict, dataclass
from datetime import date, timedelta
from pathlib import Path
from typing import Optional


_STAGE_ID_RE = re.compile(r"\bD(\d+)\b")
_ISO_DATE_RE = re.compile(r"^(\d{4})-(\d{2})-(\d{2})\.md$")


def _safe_read(path: Path) -> str:
    if not path.exists():
        return ""
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return ""


def _parse_date(p: Path) -> Optional[date]:
    m = _ISO_DATE_RE.match(p.name)
    if not m:
        return None
    try:
        return date(int(m.group(1)), int(m.group(2)),
                    int(m.group(3)))
    except ValueError:
        return None


def _stages_in(text: str) -> list[str]:
    out: list[str] = []
    for line in text.splitlines():
        if line.startswith("##") and not line.startswith("###"):
            for sid in _STAGE_ID_RE.findall(line):
                out.append(f"D{sid}")
    return out


def _normalize_did(s: str) -> str:
    m = re.match(r"^D(\d+)$", s)
    if not m:
        return s
    n = int(m.group(1))
    return f"D{n:02d}" if n < 10 else f"D{n}"


@dataclass
class StreakReport:
    n_active_days: int
    n_total_stages_first_seen: int
    longest_streak: int
    current_streak: int
    last_active_date: str
    first_active_date: str

    def to_dict(self) -> dict:
        return {
            "n_active_days": self.n_active_days,
            "n_total_stages_first_seen": self.n_total_stages_first_seen,
            "longest_streak": self.longest_streak,
            "current_streak": self.current_streak,
            "last_active_date": self.last_active_date,
            "first_active_date": self.first_active_date,
        }


def _consecutive_run(sorted_dates: list) -> int:
    if not sorted_dates:
        return 0
    longest = 1
    cur = 1
    for i in range(1, len(sorted_dates)):
        if (sorted_dates[i] - sorted_dates[i - 1]).days == 1:
            cur += 1
            longest = max(longest, cur)
        else:
            cur = 1
    return longest


def build_streak(memory_dir: Path, today: Optional[date] = None) -> StreakReport:
    if today is None:
        today = date.today()
    if not memory_dir.is_dir():
        return StreakReport(0, 0, 0, 0, "", "")
    active_days: set = set()
    first_seen_stages: set = set()
    for p in memory_dir.glob("*.md"):
        d = _parse_date(p)
        if d is None:
            continue
        active_days.add(d)
        for s in _stages_in(_safe_read(p)):
            first_seen_stages.add(_normalize_did(s))
    if not active_days:
        return StreakReport(0, len(first_seen_stages), 0, 0, "", "")
    sorted_days = sorted(active_days)
    longest = _consecutive_run(sorted_days)
    last_day = sorted_days[-1]
    current = 0
    d = last_day
    while d in active_days:
        current += 1
        d = d - timedelta(days=1)
    return StreakReport(
        n_active_days=len(active_days),
        n_total_stages_first_seen=len(first_seen_stages),
        longest_streak=longest,
        current_streak=current,
        last_active_date=last_day.isoformat(),
        first_active_date=sorted_days[0].isoformat(),
    )


def render_markdown(report: StreakReport) -> str:
    lines: list = ["# Stage Streak", ""]
    lines.append(f"*Generated by `src.analysis.stage_streak` on "
                  f"{time.strftime('%Y-%m-%d %H:%M:%S')}*\n")
    if report.n_active_days == 0:
        lines.append("*(no data)*\n")
        return "\n".join(lines)
    lines.append("## Summary\n")
    lines.append(f"- **Active days**: {report.n_active_days}")
    lines.append(f"- **Unique stages first-seen**: "
                  f"{report.n_total_stages_first_seen}")
    lines.append(f"- **Longest streak**: {report.longest_streak} days")
    lines.append(f"- **Current streak**: {report.current_streak} days")
    lines.append(f"- **First active date**: {report.first_active_date}")
    lines.append(f"- **Last active date**: {report.last_active_date}")
    lines.append("")
    return "\n".join(lines)


def render_json(report: StreakReport) -> dict:
    return {"report": report.to_dict()}


def main() -> int:
    p = argparse.ArgumentParser(description="Stage streak")
    p.add_argument("--memory_dir", type=Path,
                   default=Path("../.workbuddy/memory"))
    p.add_argument("--out", type=Path,
                   default=Path("report/stage_streak.md"))
    p.add_argument("--out_json", type=Path,
                   default=Path("report/stage_streak.json"))
    args = p.parse_args()
    report = build_streak(args.memory_dir)
    md = render_markdown(report)
    print(f"[streak] {report.n_active_days} days; "
          f"longest={report.longest_streak}; "
          f"current={report.current_streak}")
    print(md)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(md, encoding="utf-8")
    print(f"Wrote Markdown -> {args.out}")
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(
        json.dumps(render_json(report), indent=2, ensure_ascii=False),
        encoding="utf-8")
    print(f"Wrote JSON     -> {args.out_json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
