"""
Stage cadence (D46).

Reads `.workbuddy/memory/YYYY-MM-DD.md` and computes per-day stage
mention cadence, with a quality score (A-F) based on volume and
uniqueness.
"""

from __future__ import annotations

import argparse
import json
import re
import time
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass
from datetime import date
from pathlib import Path
from typing import Optional


_STAGE_ID_RE = re.compile(r"\bD(\d+)\b")
_ISO_DATE_RE = re.compile(r"^(\d{4})-(\d{2})-(\d{2})\.md$")


def _safe_read(path: Path) -> str:
    if not path.exists():
        return ""
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return ""


def _parse_date(p: Path) -> Optional[date]:
    m = _ISO_DATE_RE.match(p.name)
    if not m:
        return None
    try:
        return date(int(m.group(1)), int(m.group(2)),
                    int(m.group(3)))
    except ValueError:
        return None


def _stages_in(text: str) -> list[str]:
    out: list[str] = []
    for line in text.splitlines():
        if line.startswith("##") and not line.startswith("###"):
            for sid in _STAGE_ID_RE.findall(line):
                out.append(f"D{sid}")
    return out


def _median(xs: list) -> float:
    if not xs:
        return 0.0
    s = sorted(xs)
    n = len(s)
    if n % 2 == 1:
        return float(s[n // 2])
    return (s[n // 2 - 1] + s[n // 2]) / 2.0


@dataclass
class CadenceReport:
    n_active_days: int
    n_total_mentions: int
    n_unique_stages: int
    median_mentions_per_day: float
    cadence_score: int
    cadence_grade: str
    per_day: dict

    def to_dict(self) -> dict:
        return {
            "n_active_days": self.n_active_days,
            "n_total_mentions": self.n_total_mentions,
            "n_unique_stages": self.n_unique_stages,
            "median_mentions_per_day": self.median_mentions_per_day,
            "cadence_score": self.cadence_score,
            "cadence_grade": self.cadence_grade,
            "per_day": self.per_day,
        }


def build_cadence(memory_dir: Path) -> CadenceReport:
    if not memory_dir.is_dir():
        return CadenceReport(0, 0, 0, 0.0, 0, "F", {})
    per_day: dict = defaultdict(set)
    per_day_count: dict = defaultdict(int)
    for p in memory_dir.glob("*.md"):
        d = _parse_date(p)
        if d is None:
            continue
        for s in _stages_in(_safe_read(p)):
            per_day[d].add(s)
            per_day_count[d] += 1
    n_active = len(per_day)
    n_total = sum(per_day_count.values())
    all_stages: set = set()
    for stages in per_day.values():
        all_stages |= stages
    counts = list(per_day_count.values())
    median = _median([float(c) for c in counts]) if counts else 0.0
    # Score 0-100
    score = 0
    if n_active > 0:
        score = min(100, int(20 * n_active + 5 * n_total))
    if score >= 80:
        grade = "A"
    elif score >= 60:
        grade = "B"
    elif score >= 40:
        grade = "C"
    elif score >= 20:
        grade = "D"
    else:
        grade = "F"
    return CadenceReport(
        n_active_days=n_active,
        n_total_mentions=n_total,
        n_unique_stages=len(all_stages),
        median_mentions_per_day=median,
        cadence_score=score,
        cadence_grade=grade,
        per_day={d.isoformat(): c for d, c in sorted(per_day_count.items())},
    )


def render_markdown(report: CadenceReport) -> str:
    out: list[str] = ["# Stage Cadence", ""]
    out.append(f"*Generated by `src.analysis.stage_cadence` on "
                f"{time.strftime('%Y-%m-%d %H:%M:%S')}*\n")
    if report.n_active_days == 0:
        out.append("*(no data)*\n")
        return "\n".join(out)
    out.append("## Summary\n")
    out.append(f"- **Active days**: {report.n_active_days}")
    out.append(f"- **Total mentions**: {report.n_total_mentions}")
    out.append(f"- **Unique stages**: {report.n_unique_stages}")
    out.append(f"- **Median mentions/day**: "
                f"{report.median_mentions_per_day:.1f}")
    out.append(f"- **Cadence score**: {report.cadence_score} "
                f"(grade {report.cadence_grade})")
    out.append("")
    out.append("## Per-day\n")
    out.append("| date | mentions |")
    out.append("|---|---|")
    for d, c in report.per_day.items():
        out.append(f"| {d} | {c} |")
    out.append("")
    return "\n".join(out)


def render_json(report: CadenceReport) -> dict:
    return {"report": report.to_dict()}


def main() -> int:
    p = argparse.ArgumentParser(description="Stage cadence")
    p.add_argument("--memory_dir", type=Path,
                   default=Path("../.workbuddy/memory"))
    p.add_argument("--out", type=Path,
                   default=Path("report/stage_cadence.md"))
    p.add_argument("--out_json", type=Path,
                   default=Path("report/stage_cadence.json"))
    args = p.parse_args()
    report = build_cadence(args.memory_dir)
    md = render_markdown(report)
    print(f"[cadence] {report.n_active_days} active days; "
          f"score={report.cadence_score} ({report.cadence_grade})")
    print(md)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(md, encoding="utf-8")
    print(f"Wrote Markdown -> {args.out}")
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(
        json.dumps(render_json(report), indent=2, ensure_ascii=False),
        encoding="utf-8")
    print(f"Wrote JSON     -> {args.out_json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
