"""
Stage suggestion (D47).

Reads `.workbuddy/memory/YYYY-MM-DD.md` and produces 3 actionable
suggestions based on project state: which stages to do next, which
to finish, and which orphan stages to address.
"""

from __future__ import annotations

import argparse
import json
import re
import time
from collections import Counter
from dataclasses import asdict, dataclass
from datetime import date
from pathlib import Path
from typing import Optional


_STAGE_ID_RE = re.compile(r"\bD(\d+)\b")
_ISO_DATE_RE = re.compile(r"^(\d{4})-(\d{2})-(\d{2})\.md$")


def _safe_read(path: Path) -> str:
    if not path.exists():
        return ""
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return ""


def _parse_date(p: Path) -> Optional[date]:
    m = _ISO_DATE_RE.match(p.name)
    if not m:
        return None
    try:
        return date(int(m.group(1)), int(m.group(2)),
                    int(m.group(3)))
    except ValueError:
        return None


def _stages_in(text: str) -> list[str]:
    out: list[str] = []
    for line in text.splitlines():
        if line.startswith("##") and not line.startswith("###"):
            for sid in _STAGE_ID_RE.findall(line):
                out.append(f"D{sid}")
    return out


def _normalize_did(s: str) -> str:
    m = re.match(r"^D(\d+)$", s)
    if not m:
        return s
    n = int(m.group(1))
    return f"D{n:02d}" if n < 10 else f"D{n}"


def collect_suggestions(memory_dir: Path) -> list:
    if not memory_dir.is_dir():
        return []
    mentions: Counter = Counter()
    for p in memory_dir.glob("*.md"):
        for s in _stages_in(_safe_read(p)):
            mentions[_normalize_did(s)] += 1
    if not mentions:
        return []
    max_n = max(mentions.values())
    max_id = max(int(re.match(r"^D(\d+)$", s).group(1))
                  for s in mentions.keys())
    suggestions = []
    # 1. Gap: a high-id D with no/few mentions
    orphans = [(s, c) for s, c in mentions.items() if c == 1]
    if orphans:
        target = max(orphans, key=lambda x: int(x[0][1:]))
        suggestions.append({
            "type": "gap",
            "stage": target[0],
            "reason": (f"high-id stage {target[0]} mentioned only once; "
                        f"consider documenting it"),
        })
    # 2. Next: stage right after the max mentioned
    next_id = f"D{max_id + 1:02d}"
    suggestions.append({
        "type": "next",
        "stage": next_id,
        "reason": (f"natural next stage after D{max_id:02d}; "
                    f"pick a new feature/fix"),
    })
    # 3. Process loop: many orphan stages
    if len(orphans) > 5:
        suggestions.append({
            "type": "process_loop",
            "stage": "(project-wide)",
            "reason": (f"{len(orphans)} stages mentioned only once; "
                        f"consider a weekly review cycle"),
        })
    return suggestions


def render_markdown(suggestions: list) -> str:
    out: list[str] = ["# Stage Suggestions", ""]
    out.append(f"*Generated by `src.analysis.stage_suggestion` on "
                f"{time.strftime('%Y-%m-%d %H:%M:%S')}*\n")
    if not suggestions:
        out.append("*(no data)*\n")
        return "\n".join(out)
    out.append("## Suggestions\n")
    for i, s in enumerate(suggestions, 1):
        out.append(f"{i}. **{s['type']}** - `{s['stage']}`: "
                    f"{s['reason']}")
    out.append("")
    return "\n".join(out)


def render_json(suggestions: list) -> dict:
    return {"suggestions": suggestions}


def main() -> int:
    p = argparse.ArgumentParser(description="Stage suggestions")
    p.add_argument("--memory_dir", type=Path,
                   default=Path("../.workbuddy/memory"))
    p.add_argument("--out", type=Path,
                   default=Path("report/stage_suggestion.md"))
    p.add_argument("--out_json", type=Path,
                   default=Path("report/stage_suggestion.json"))
    args = p.parse_args()
    suggestions = collect_suggestions(args.memory_dir)
    md = render_markdown(suggestions)
    print(f"[suggestion] {len(suggestions)} suggestions")
    print(md)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(md, encoding="utf-8")
    print(f"Wrote Markdown -> {args.out}")
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(
        json.dumps(render_json(suggestions), indent=2,
                    ensure_ascii=False),
        encoding="utf-8")
    print(f"Wrote JSON     -> {args.out_json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
