"""
Stage density curve (D56).

Reads `.workbuddy/memory/YYYY-MM-DD.md` and produces a cumulative
mention distribution per stage — how many of the total mentions
fall in the first 25% / 50% / 75% / 100% of the stage's active time.
"""

from __future__ import annotations

import argparse
import json
import re
import time
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass
from datetime import date
from pathlib import Path
from typing import Optional


_STAGE_ID_RE = re.compile(r"\bD(\d+)\b")
_ISO_DATE_RE = re.compile(r"^(\d{4})-(\d{2})-(\d{2})\.md$")


def _safe_read(path: Path) -> str:
    if not path.exists():
        return ""
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return ""


def _parse_date(p: Path) -> Optional[date]:
    m = _ISO_DATE_RE.match(p.name)
    if not m:
        return None
    try:
        return date(int(m.group(1)), int(m.group(2)),
                    int(m.group(3)))
    except ValueError:
        return None


def _stages_in(text: str) -> list[str]:
    out: list[str] = []
    for line in text.splitlines():
        if line.startswith("##") and not line.startswith("###"):
            for sid in _STAGE_ID_RE.findall(line):
                out.append(f"D{sid}")
    return out


@dataclass
class DensityCurve:
    id: str
    mention_count: int
    n_active_days: int
    span_days: int
    first_quarter_share: float
    mid_share: float
    last_quarter_share: float
    front_loaded: bool
    back_loaded: bool
    first_date: str
    last_date: str

    def to_row(self) -> tuple:
        return (self.id, str(self.mention_count),
                str(self.n_active_days), str(self.span_days),
                f"{self.first_quarter_share:.2f}",
                f"{self.mid_share:.2f}",
                f"{self.last_quarter_share:.2f}",
                "Y" if self.front_loaded else ".",
                "Y" if self.back_loaded else ".")


def _quartile_shares(mention_per_day: list) -> tuple:
    n_days = len(mention_per_day)
    if n_days == 0:
        return (0.0, 0.0, 0.0)
    if n_days == 1:
        return (1.0, 0.0, 0.0)
    total = sum(mention_per_day)
    if total == 0:
        return (0.0, 0.0, 0.0)
    q1 = max(1, n_days // 4)
    q3 = max(q1 + 1, 3 * n_days // 4)
    first_q = sum(mention_per_day[:q1]) / total
    mid = sum(mention_per_day[q1:q3]) / total
    last_q = sum(mention_per_day[q3:]) / total
    return (first_q, mid, last_q)


def collect_curves(memory_dir: Path) -> list:
    if not memory_dir.is_dir():
        return []
    stage_to_days: dict = defaultdict(Counter)
    for p in memory_dir.glob("*.md"):
        d = _parse_date(p)
        if d is None:
            continue
        for s in _stages_in(_safe_read(p)):
            stage_to_days[s][d] += 1
    if not stage_to_days:
        return []
    out: list = []
    for stage in sorted(stage_to_days.keys()):
        per_day = stage_to_days[stage]
        sorted_dates = sorted(per_day.keys())
        n_active = len(sorted_dates)
        total_mentions = sum(per_day.values())
        span = (sorted_dates[-1] - sorted_dates[0]).days if n_active > 1 else 0
        per_day_counts = [per_day[d] for d in sorted_dates]
        fq, m, lq = _quartile_shares(per_day_counts)
        out.append(DensityCurve(
            id=stage,
            mention_count=total_mentions,
            n_active_days=n_active,
            span_days=span,
            first_quarter_share=fq,
            mid_share=m,
            last_quarter_share=lq,
            front_loaded=(fq > 0.5),
            back_loaded=(lq > 0.5),
            first_date=sorted_dates[0].isoformat() if sorted_dates else "",
            last_date=sorted_dates[-1].isoformat() if sorted_dates else "",
        ))
    out.sort(key=lambda c: (-c.mention_count, c.id))
    return out


def render_markdown(curves: list) -> str:
    out: list[str] = ["# Stage Density Curve", ""]
    out.append(f"*Generated by `src.analysis.stage_density_curve` on "
                f"{time.strftime('%Y-%m-%d %H:%M:%S')}*\n")
    if not curves:
        out.append("*(no data)*\n")
        return "\n".join(out)
    n_total = len(curves)
    n_front = sum(1 for c in curves if c.front_loaded)
    n_back = sum(1 for c in curves if c.back_loaded)
    out.append("## Summary\n")
    out.append(f"- **Stages**: {n_total}")
    out.append(f"- **Front-loaded (first_q > 0.5)**: {n_front}")
    out.append(f"- **Back-loaded (last_q > 0.5)**: {n_back}")
    out.append(f"- **Total mentions**: "
                f"{sum(c.mention_count for c in curves)}")
    out.append("")
    out.append("## Per-stage density curve (top 20 by mentions)\n")
    out.append("| id | mentions | days | span | first_q | mid | last_q | front | back |")
    out.append("|---|---|---|---|---|---|---|---|---|")
    for c in curves[:20]:
        out.append("| " + " | ".join(c.to_row()) + " |")
    out.append("")
    front = [c for c in curves if c.front_loaded and c.mention_count >= 2]
    back = [c for c in curves if c.back_loaded and c.mention_count >= 2]
    if front:
        out.append("## Front-loaded stages (first quarter > 50%)\n")
        for c in front[:10]:
            out.append(f"- **{c.id}**: {c.mention_count} mentions, "
                        f"first_q={c.first_quarter_share:.0%}")
        out.append("")
    if back:
        out.append("## Back-loaded stages (last quarter > 50%)\n")
        for c in back[:10]:
            out.append(f"- **{c.id}**: {c.mention_count} mentions, "
                        f"last_q={c.last_quarter_share:.0%}")
        out.append("")
    return "\n".join(out)


def render_json(curves: list) -> dict:
    return {
        "n_stages": len(curves),
        "n_front_loaded": sum(1 for c in curves if c.front_loaded),
        "n_back_loaded": sum(1 for c in curves if c.back_loaded),
        "curves": [asdict(c) for c in curves],
    }


def main() -> int:
    p = argparse.ArgumentParser(
        description="Stage density curve (front/back-loaded)")
    p.add_argument("--memory_dir", type=Path,
                   default=Path("../.workbuddy/memory"))
    p.add_argument("--out", type=Path,
                   default=Path("report/stage_density_curve.md"))
    p.add_argument("--out_json", type=Path,
                   default=Path("report/stage_density_curve.json"))
    args = p.parse_args()
    curves = collect_curves(args.memory_dir)
    md = render_markdown(curves)
    print(f"[density_curve] {len(curves)} stages; "
          f"front={sum(1 for c in curves if c.front_loaded)}, "
          f"back={sum(1 for c in curves if c.back_loaded)}")
    print(md)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(md, encoding="utf-8")
    print(f"Wrote Markdown -> {args.out}")
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(
        json.dumps(render_json(curves), indent=2, ensure_ascii=False),
        encoding="utf-8")
    print(f"Wrote JSON     -> {args.out_json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
