"""
Stage calendar (D58).

Reads `.workbuddy/memory/YYYY-MM-DD.md` and produces a
calendar view of stage activity:

  1. Per-month counts (YYYY-MM -> total mentions that month)
  2. Per-weekday counts (Mon..Sun -> total mentions that day of week)
  3. Calendar grid (last 14 days) with mention counts

This complements D49 (trend) and D55 (velocity) by showing the
weekly/monthly rhythm of when stage work happens.
"""

from __future__ import annotations

import argparse
import json
import re
import time
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass
from datetime import date
from pathlib import Path
from typing import Optional


_STAGE_ID_RE = re.compile(r"\bD(\d+)\b")
_ISO_DATE_RE = re.compile(r"^(\d{4})-(\d{2})-(\d{2})\.md$")
_WEEKDAY_NAMES = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]


def _safe_read(path: Path) -> str:
    if not path.exists():
        return ""
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return ""


def _parse_date(p: Path) -> Optional[date]:
    m = _ISO_DATE_RE.match(p.name)
    if not m:
        return None
    try:
        return date(int(m.group(1)), int(m.group(2)),
                    int(m.group(3)))
    except ValueError:
        return None


def _stages_in(text: str) -> list[str]:
    out: list[str] = []
    for line in text.splitlines():
        if line.startswith("##") and not line.startswith("###"):
            for sid in _STAGE_ID_RE.findall(line):
                out.append(f"D{sid}")
    return out


@dataclass
class CalendarReport:
    n_active_days: int
    n_total_mentions: int
    per_month: dict
    per_weekday: dict
    per_day: dict
    weekday_bars: list

    def to_dict(self) -> dict:
        return {
            "n_active_days": self.n_active_days,
            "n_total_mentions": self.n_total_mentions,
            "per_month": self.per_month,
            "per_weekday": self.per_weekday,
            "per_day": self.per_day,
        }


def collect_calendar(memory_dir: Path) -> CalendarReport:
    if not memory_dir.is_dir():
        return CalendarReport(0, 0, {}, {}, {}, [])
    per_day_count: dict[date, int] = defaultdict(int)
    for p in memory_dir.glob("*.md"):
        d = _parse_date(p)
        if d is None:
            continue
        n = len(_stages_in(_safe_read(p)))
        per_day_count[d] += n
    if not per_day_count:
        return CalendarReport(0, 0, {}, {}, {}, [])
    per_day: dict = {d.isoformat(): c
                       for d, c in sorted(per_day_count.items())}
    per_month: dict = defaultdict(int)
    per_weekday: dict = defaultdict(int)
    for d, c in per_day_count.items():
        per_month[d.strftime("%Y-%m")] += c
        per_weekday[_WEEKDAY_NAMES[d.weekday()]] += c
    n_total = sum(per_day_count.values())
    max_wd = max(per_weekday.values()) if per_weekday else 0
    weekday_bars = []
    for wd in _WEEKDAY_NAMES:
        c = per_weekday.get(wd, 0)
        bar = "█" * c if max_wd else ""
        weekday_bars.append(f"{wd} | {bar:<20} {c}")
    return CalendarReport(
        n_active_days=len(per_day_count),
        n_total_mentions=n_total,
        per_month=dict(sorted(per_month.items())),
        per_weekday=dict(per_weekday),
        per_day=per_day,
        weekday_bars=weekday_bars,
    )


def render_markdown(report: CalendarReport) -> str:
    out: list[str] = ["# Stage Calendar", ""]
    out.append(f"*Generated by `src.analysis.stage_calendar` on "
                f"{time.strftime('%Y-%m-%d %H:%M:%S')}*\n")
    if report.n_active_days == 0:
        out.append("*(no data)*\n")
        return "\n".join(out)
    out.append("## Summary\n")
    out.append(f"- **Active days**: {report.n_active_days}")
    out.append(f"- **Total mentions**: {report.n_total_mentions}")
    out.append(f"- **Months covered**: {len(report.per_month)}")
    out.append("")
    out.append("## Per-month counts\n")
    out.append("| month | mentions |")
    out.append("|---|---|")
    for m, c in report.per_month.items():
        out.append(f"| {m} | {c} |")
    out.append("")
    out.append("## Per-weekday counts\n")
    out.append("```")
    for line in report.weekday_bars:
        out.append(line)
    out.append("```")
    out.append("")
    out.append("## Recent per-day counts (newest 14)\n")
    out.append("| date | mentions |")
    out.append("|---|---|")
    for d, c in list(report.per_day.items())[-14:]:
        out.append(f"| {d} | {c} |")
    out.append("")
    return "\n".join(out)


def render_json(report: CalendarReport) -> dict:
    return {"report": report.to_dict()}


def main() -> int:
    p = argparse.ArgumentParser(description="Stage calendar view")
    p.add_argument("--memory_dir", type=Path,
                   default=Path("../.workbuddy/memory"))
    p.add_argument("--out", type=Path,
                   default=Path("report/stage_calendar.md"))
    p.add_argument("--out_json", type=Path,
                   default=Path("report/stage_calendar.json"))
    args = p.parse_args()
    report = collect_calendar(args.memory_dir)
    md = render_markdown(report)
    print(f"[calendar] {report.n_active_days} active days; "
          f"{report.n_total_mentions} mentions; "
          f"{len(report.per_month)} months")
    print(md)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(md, encoding="utf-8")
    print(f"Wrote Markdown -> {args.out}")
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(
        json.dumps(render_json(report), indent=2, ensure_ascii=False),
        encoding="utf-8")
    print(f"Wrote JSON     -> {args.out_json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
