"""
Stage grep (D43).

Searches all files in `src/`, `tests/`, `report/` for occurrences of
Dxx stage IDs and reports per-file and per-stage counts.
"""

from __future__ import annotations

import argparse
import json
import re
import time
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Optional


_STAGE_ID_RE = re.compile(r"\bD(\d+)\b")


def _safe_read(path: Path) -> str:
    if not path.exists():
        return ""
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return ""


def _normalize_did(s: str) -> str:
    m = re.match(r"^D(\d+)$", s)
    if not m:
        return s
    n = int(m.group(1))
    return f"D{n:02d}" if n < 10 else f"D{n}"


@dataclass
class GrepReport:
    n_files: int
    n_distinct_stages: int
    n_mentions: int
    per_file: list  # (path, n_stages, stages)
    per_stage: dict  # stage -> count

    def to_dict(self) -> dict:
        return {
            "n_files": self.n_files,
            "n_distinct_stages": self.n_distinct_stages,
            "n_mentions": self.n_mentions,
            "per_file": [list(p) for p in self.per_file],
            "per_stage": self.per_stage,
        }


def scan_directory(root: Path) -> list:
    if not root.is_dir():
        return []
    out: list = []
    for p in root.rglob("*"):
        if not p.is_file():
            continue
        if p.suffix not in (".py", ".md", ".txt", ".json"):
            continue
        text = _safe_read(p)
        stages = set()
        for m in _STAGE_ID_RE.finditer(text):
            stages.add(_normalize_did(f"D{m.group(1)}"))
        if stages:
            out.append((p, sorted(stages)))
    return out


def build_grep(project_root: Path) -> GrepReport:
    sources = ["src", "tests", "report"]
    per_file: list = []
    per_stage: Counter = Counter()
    n_files = 0
    for sub in sources:
        sub_path = project_root / sub
        if not sub_path.is_dir():
            continue
        for p, stages in scan_directory(sub_path):
            per_file.append((str(p.relative_to(project_root)), len(stages),
                              stages))
            for s in stages:
                per_stage[s] += 1
            n_files += 1
    per_file.sort(key=lambda x: -x[1])
    n_mentions = sum(per_stage.values())
    return GrepReport(
        n_files=n_files,
        n_distinct_stages=len(per_stage),
        n_mentions=n_mentions,
        per_file=per_file,
        per_stage=dict(per_stage),
    )


def render_markdown(report: GrepReport) -> str:
    out: list[str] = ["# Stage Grep", ""]
    out.append(f"*Generated by `src.analysis.stage_grep` on "
                f"{time.strftime('%Y-%m-%d %H:%M:%S')}*\n")
    if report.n_files == 0:
        out.append("*(no files with stage references)*\n")
        return "\n".join(out)
    out.append("## Summary\n")
    out.append(f"- **Files with stage references**: {report.n_files}")
    out.append(f"- **Distinct stages**: {report.n_distinct_stages}")
    out.append(f"- **Total stage references**: {report.n_mentions}")
    out.append("")
    out.append("## Per-file (top 20)\n")
    out.append("| file | n_stages | stages |")
    out.append("|---|---|---|")
    for path, n, stages in report.per_file[:20]:
        out.append(f"| {path} | {n} | {', '.join(stages)} |")
    out.append("")
    out.append("## Per-stage (top 20)\n")
    out.append("| stage | count |")
    out.append("|---|---|")
    for s, c in sorted(report.per_stage.items(),
                         key=lambda x: -x[1])[:20]:
        out.append(f"| {s} | {c} |")
    out.append("")
    return "\n".join(out)


def render_json(report: GrepReport) -> dict:
    return {"report": report.to_dict()}


def main() -> int:
    p = argparse.ArgumentParser(
        description="Stage grep (search src/ tests/ report/ for Dxx)")
    p.add_argument("--project_root", type=Path, default=Path("."))
    p.add_argument("--out", type=Path,
                   default=Path("report/stage_grep.md"))
    p.add_argument("--out_json", type=Path,
                   default=Path("report/stage_grep.json"))
    args = p.parse_args()
    report = build_grep(args.project_root)
    md = render_markdown(report)
    print(f"[grep] {report.n_files} files; "
          f"{report.n_distinct_stages} distinct stages; "
          f"{report.n_mentions} refs")
    print(md)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(md, encoding="utf-8")
    print(f"Wrote Markdown -> {args.out}")
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(
        json.dumps(render_json(report), indent=2, ensure_ascii=False),
        encoding="utf-8")
    print(f"Wrote JSON     -> {args.out_json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
