"""
Stage maturity (D54).

Combines three signals to score each Dxx stage on a 0-3 maturity
scale:
  - mentioned_in_memory
  - implemented_in_code  (## Dxx in src/**.py)
  - documented_in_readme  (**Dxx** in README.md)
"""

from __future__ import annotations

import argparse
import json
import re
import time
from collections import Counter
from dataclasses import asdict, dataclass
from datetime import date
from pathlib import Path
from typing import Optional


_STAGE_ID_RE = re.compile(r"\bD(\d+)\b")
_ISO_DATE_RE = re.compile(r"^(\d{4})-(\d{2})-(\d{2})\.md$")
_HEADING_DOC_RE = re.compile(r"^##\s+D(\d+)")
_BOLD_RE = re.compile(r"\*\*D(\d+)\*\*")


def _safe_read(path: Path) -> str:
    if not path.exists():
        return ""
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return ""


def _parse_date(p: Path) -> Optional[date]:
    m = _ISO_DATE_RE.match(p.name)
    if not m:
        return None
    try:
        return date(int(m.group(1)), int(m.group(2)),
                    int(m.group(3)))
    except ValueError:
        return None


def _stages_in(text: str) -> list[str]:
    out: list[str] = []
    for line in text.splitlines():
        if line.startswith("##") and not line.startswith("###"):
            for sid in _STAGE_ID_RE.findall(line):
                out.append(f"D{sid}")
    return out


def _normalize_did(s: str) -> str:
    m = re.match(r"^D(\d+)$", s)
    if not m:
        return s
    n = int(m.group(1))
    return f"D{n:02d}" if n < 10 else f"D{n}"


@dataclass
class MaturityItem:
    id: str
    in_memory: bool
    in_code: bool
    in_readme: bool
    score: int
    n_mentions: int = 0

    def to_row(self) -> tuple:
        return (self.id,
                "Y" if self.in_memory else ".",
                "Y" if self.in_code else ".",
                "Y" if self.in_readme else ".",
                str(self.score),
                str(self.n_mentions))


def _scan_memory(memory_dir: Path) -> tuple:
    mentioned: set = set()
    mentions: Counter = Counter()
    if not memory_dir.is_dir():
        return mentioned, mentions
    for p in memory_dir.glob("*.md"):
        for s in _stages_in(_safe_read(p)):
            ns = _normalize_did(s)
            mentioned.add(ns)
            mentions[ns] += 1
    return mentioned, mentions


def _scan_code(project_root: Path) -> set:
    out: set = set()
    src = project_root / "src"
    if not src.is_dir():
        return out
    for f in src.rglob("*.py"):
        for line in _safe_read(f).splitlines():
            m = _HEADING_DOC_RE.match(line)
            if m:
                out.add(_normalize_did(f"D{m.group(1)}"))
    return out


def _scan_readme(project_root: Path) -> set:
    out: set = set()
    for name in ("README.md", "readme.md"):
        text = _safe_read(project_root / name)
        if text:
            for m in _BOLD_RE.finditer(text):
                out.add(_normalize_did(f"D{m.group(1)}"))
    return out


def build_maturity(*, memory_dir: Path, project_root: Path) -> list:
    mem_stages, mentions = _scan_memory(memory_dir)
    code_stages = _scan_code(project_root)
    readme_stages = _scan_readme(project_root)
    all_stages = mem_stages | code_stages | readme_stages
    out: list = []
    for sid in sorted(all_stages):
        in_m = sid in mem_stages
        in_c = sid in code_stages
        in_r = sid in readme_stages
        score = (1 if in_m else 0) + (1 if in_c else 0) + (1 if in_r else 0)
        out.append(MaturityItem(
            id=sid, in_memory=in_m, in_code=in_c, in_readme=in_r,
            score=score, n_mentions=mentions.get(sid, 0),
        ))
    return out


def render_markdown(items: list) -> str:
    out: list[str] = ["# Stage Maturity", ""]
    out.append(f"*Generated by `src.analysis.stage_maturity` on "
                f"{time.strftime('%Y-%m-%d %H:%M:%S')}*\n")
    if not items:
        out.append("*(no data)*\n")
        return "\n".join(out)
    n = len(items)
    full = sum(1 for i in items if i.score == 3)
    partial = sum(1 for i in items if i.score == 2)
    one = sum(1 for i in items if i.score == 1)
    zero = sum(1 for i in items if i.score == 0)
    out.append("## Summary\n")
    out.append(f"- **Total stages**: {n}")
    out.append(f"- **Fully mature (3)**: {full}")
    out.append(f"- **Partial (2)**: {partial}")
    out.append(f"- **One-channel (1)**: {one}")
    out.append(f"- **Barely there (0)**: {zero}")
    if n:
        out.append(f"- **Maturity score**: "
                    f"{(3 * full + 2 * partial + 1 * one) / (3 * n):.1%} "
                    f"of maximum")
    out.append("")
    out.append("## Per-stage maturity\n")
    out.append("| id | memory | code | readme | score | mentions |")
    out.append("|---|---|---|---|---|---|")
    for it in items:
        out.append("| " + " | ".join(it.to_row()) + " |")
    out.append("")
    return "\n".join(out)


def render_json(items: list) -> dict:
    return {
        "n_stages": len(items),
        "n_full_mature": sum(1 for i in items if i.score == 3),
        "n_partial": sum(1 for i in items if i.score == 2),
        "n_one_channel": sum(1 for i in items if i.score == 1),
        "n_barely": sum(1 for i in items if i.score == 0),
        "items": [asdict(i) for i in items],
    }


def main() -> int:
    p = argparse.ArgumentParser(description="Stage maturity score")
    p.add_argument("--memory_dir", type=Path,
                   default=Path("../.workbuddy/memory"))
    p.add_argument("--readme", type=Path, default=Path("README.md"))
    p.add_argument("--project_root", type=Path, default=Path("."))
    p.add_argument("--out", type=Path,
                   default=Path("report/stage_maturity.md"))
    p.add_argument("--out_json", type=Path,
                   default=Path("report/stage_maturity.json"))
    args = p.parse_args()
    items = build_maturity(memory_dir=args.memory_dir,
                              project_root=args.project_root)
    md = render_markdown(items)
    print(f"[maturity] {len(items)} stages scored")
    print(md)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(md, encoding="utf-8")
    print(f"Wrote Markdown -> {args.out}")
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(
        json.dumps(render_json(items), indent=2, ensure_ascii=False),
        encoding="utf-8")
    print(f"Wrote JSON     -> {args.out_json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
