"""
Stage clusters (D51).

Greedy community detection on the stage co-occurrence graph:
  - Sort pairs by count desc
  - Merge clusters when both stages appear
  - Per-cluster density = 2E / n(n-1)
  - Singletons detection
"""

from __future__ import annotations

import argparse
import json
import re
import time
from collections import defaultdict
from dataclasses import asdict, dataclass
from itertools import combinations
from pathlib import Path
from typing import Optional


_STAGE_ID_RE = re.compile(r"\bD(\d+)\b")
_ISO_DATE_RE = re.compile(r"^(\d{4})-(\d{2})-(\d{2})\.md$")


def _safe_read(path: Path) -> str:
    if not path.exists():
        return ""
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return ""


def _parse_date(p: Path) -> Optional[object]:
    from datetime import date
    m = _ISO_DATE_RE.match(p.name)
    if not m:
        return None
    try:
        return date(int(m.group(1)), int(m.group(2)),
                    int(m.group(3)))
    except ValueError:
        return None


def _stages_in(text: str) -> list[str]:
    out: list[str] = []
    for line in text.splitlines():
        if line.startswith("##") and not line.startswith("###"):
            for sid in _STAGE_ID_RE.findall(line):
                out.append(f"D{sid}")
    return out


def collect_file_stages(memory_dir: Path) -> list:
    if not memory_dir.is_dir():
        return []
    out: list = []
    for p in memory_dir.glob("*.md"):
        stages = _stages_in(_safe_read(p))
        if stages:
            out.append(sorted(set(stages)))
    return out


def build_pair_counts(file_stages: list) -> dict:
    pair_counts: dict = defaultdict(int)
    for stages in file_stages:
        for a, b in combinations(stages, 2):
            pair_counts[frozenset({a, b})] += 1
    return pair_counts


def greedy_cluster(pair_counts: dict, all_stages: set) -> list:
    sorted_pairs = sorted(pair_counts.items(), key=lambda x: -x[1])
    stage_to_cluster: dict = {}
    clusters: list = []
    for pair, _c in sorted_pairs:
        a, b = list(pair)
        ca = stage_to_cluster.get(a)
        cb = stage_to_cluster.get(b)
        if ca is None and cb is None:
            new_id = len(clusters)
            clusters.append({a, b})
            stage_to_cluster[a] = new_id
            stage_to_cluster[b] = new_id
        elif ca is None and cb is not None:
            clusters[cb].add(a)
            stage_to_cluster[a] = cb
        elif ca is not None and cb is None:
            clusters[ca].add(b)
            stage_to_cluster[b] = ca
        else:
            if ca == cb:
                continue
            target, source = (ca, cb) if ca < cb else (cb, ca)
            for s in clusters[source]:
                stage_to_cluster[s] = target
            clusters[target].update(clusters[source])
            clusters[source] = set()
    for s in all_stages:
        if s not in stage_to_cluster:
            new_id = len(clusters)
            clusters.append({s})
            stage_to_cluster[s] = new_id
    return [c for c in clusters if c]


@dataclass
class ClusterStats:
    cid: int
    size: int
    n_internal_edges: int
    density: float

    def to_row(self) -> tuple:
        return (f"C{self.cid:02d}", str(self.size),
                str(self.n_internal_edges), f"{self.density:.2%}")


def count_internal_edges(cluster: set, pair_counts: dict) -> int:
    total = 0
    for a, b in combinations(sorted(cluster), 2):
        total += pair_counts.get(frozenset({a, b}), 0)
    return total


def build_clusters(memory_dir: Path) -> tuple:
    file_stages = collect_file_stages(memory_dir)
    all_stages = {s for fs in file_stages for s in fs}
    pair_counts = build_pair_counts(file_stages)
    clusters = greedy_cluster(pair_counts, all_stages)
    stats: list = []
    for cid, c in enumerate(clusters):
        n = len(c)
        n_int = count_internal_edges(c, pair_counts) if n > 1 else 0
        dens = (2 * n_int / (n * (n - 1))) if n > 1 else 0.0
        stats.append(ClusterStats(
            cid=cid, size=n,
            n_internal_edges=n_int, density=dens,
        ))
    stats.sort(key=lambda s: -s.size)
    n_files = len(file_stages)
    n_pairs = len(pair_counts)
    n_total = sum(pair_counts.values())
    density = (n_total / (n_pairs * 1.0)) if n_pairs else 0.0
    n_singletons = sum(1 for s in stats if s.size == 1)
    return clusters, stats, n_files, n_pairs, n_total, density, n_singletons


def render_markdown(clusters: list, stats: list, n_files: int,
                     n_pairs: int, n_total: int, density: float,
                     n_singletons: int) -> str:
    out: list[str] = ["# Stage Clusters", ""]
    out.append(f"*Generated by `src.analysis.stage_clusters` on "
                f"{time.strftime('%Y-%m-%d %H:%M:%S')}*\n")
    if not clusters:
        out.append("*(no data)*\n")
        return "\n".join(out)
    out.append("## Summary\n")
    out.append(f"- **Files scanned**: {n_files}")
    out.append(f"- **Unique stages**: "
                f"{sum(s.size for s in stats)}")
    out.append(f"- **Pairs (edges)**: {n_pairs}")
    out.append(f"- **Total edge weight**: {n_total}")
    out.append(f"- **Edge density (avg weight per pair)**: "
                f"{density:.2f}")
    out.append(f"- **Clusters**: {len(clusters)}")
    out.append(f"- **Singletons**: {n_singletons}")
    out.append("")
    out.append("## Per-cluster stats\n")
    out.append("| cluster | size | internal_edges | density |")
    out.append("|---|---|---|---|")
    for s in stats:
        out.append("| " + " | ".join(s.to_row()) + " |")
    out.append("")
    return "\n".join(out)


def render_json(clusters: list, stats: list, n_files: int,
                 n_pairs: int, n_total: int, density: float,
                 n_singletons: int) -> dict:
    return {
        "n_files": n_files,
        "n_stages": sum(s.size for s in stats),
        "n_pairs": n_pairs,
        "n_total_edges": n_total,
        "density": density,
        "n_clusters": len(clusters),
        "n_singletons": n_singletons,
        "clusters": [asdict(s) for s in stats],
    }


def main() -> int:
    p = argparse.ArgumentParser(
        description="Stage clusters (greedy community detection)")
    p.add_argument("--memory_dir", type=Path,
                   default=Path("../.workbuddy/memory"))
    p.add_argument("--out", type=Path,
                   default=Path("report/stage_clusters.md"))
    p.add_argument("--out_json", type=Path,
                   default=Path("report/stage_clusters.json"))
    args = p.parse_args()
    clusters, stats, n_files, n_pairs, n_total, density, n_singletons = (
        build_clusters(args.memory_dir))
    md = render_markdown(clusters, stats, n_files, n_pairs, n_total,
                           density, n_singletons)
    print(f"[clusters] {len(clusters)} clusters, "
          f"{n_singletons} singletons")
    print(md)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(md, encoding="utf-8")
    print(f"Wrote Markdown -> {args.out}")
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(
        json.dumps(render_json(clusters, stats, n_files, n_pairs,
                                n_total, density, n_singletons),
                    indent=2, ensure_ascii=False),
        encoding="utf-8")
    print(f"Wrote JSON     -> {args.out_json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
