"""
Stage backlog (D52).

Combines D45 (timeline first-seen) + D43 (stage_grep project scan)
+ D44 (stage_coverage) to produce a backlog of "stages mentioned
in memory/ or README but not yet actually implemented" in src/.

Provides:
  - backlog = mentioned_in_memory_or_readme - in_code
  - bonus = in_code - mentioned
  - priority = mentions / (days_since_first_seen + 1) * 10
"""

from __future__ import annotations

import argparse
import json
import re
import time
from collections import Counter
from dataclasses import asdict, dataclass
from datetime import date
from pathlib import Path
from typing import Optional


_STAGE_ID_RE = re.compile(r"\bD(\d+)\b")
_ISO_DATE_RE = re.compile(r"^(\d{4})-(\d{2})-(\d{2})\.md$")
_HEADING_DOC_RE = re.compile(r"^##\s+D(\d+)")
_BOLD_RE = re.compile(r"\*\*D(\d+)\*\*")


def _safe_read(path: Path) -> str:
    if not path.exists():
        return ""
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return ""


def _parse_date(p: Path) -> Optional[date]:
    m = _ISO_DATE_RE.match(p.name)
    if not m:
        return None
    try:
        return date(int(m.group(1)), int(m.group(2)),
                    int(m.group(3)))
    except ValueError:
        return None


def _stages_in(text: str) -> list[str]:
    out: list[str] = []
    for line in text.splitlines():
        if line.startswith("##") and not line.startswith("###"):
            for sid in _STAGE_ID_RE.findall(line):
                out.append(f"D{sid}")
    return out


def _normalize_did(s: str) -> str:
    m = re.match(r"^D(\d+)$", s)
    if not m:
        return s
    n = int(m.group(1))
    return f"D{n:02d}" if n < 10 else f"D{n}"


@dataclass
class BacklogItem:
    id: str
    n_mentions: int
    first_seen: str
    days_since_first_seen: int
    in_readme: bool
    priority_score: float

    def to_row(self) -> tuple:
        return (self.id, str(self.n_mentions),
                self.first_seen, str(self.days_since_first_seen),
                f"{self.priority_score:.2f}")


def _scan_project_stages(project_root: Path) -> set:
    out: set = set()
    src = project_root / "src"
    if not src.is_dir():
        return out
    for f in src.rglob("*.py"):
        for line in _safe_read(f).splitlines():
            m = _HEADING_DOC_RE.match(line)
            if m:
                out.add(_normalize_did(f"D{m.group(1)}"))
    return out


def _scan_readme_stages(project_root: Path) -> set:
    out: set = set()
    for name in ("README.md", "readme.md"):
        text = _safe_read(project_root / name)
        if text:
            for m in _BOLD_RE.finditer(text):
                out.add(_normalize_did(f"D{m.group(1)}"))
    return out


def _scan_memory_stages(memory_dir: Path) -> tuple:
    mentions: Counter = Counter()
    first_seen: dict = {}
    if not memory_dir.is_dir():
        return mentions, first_seen
    for p in sorted(memory_dir.glob("*.md")):
        d = _parse_date(p)
        if d is None:
            continue
        for s in _stages_in(_safe_read(p)):
            ns = _normalize_did(s)
            mentions[ns] += 1
            if ns not in first_seen:
                first_seen[ns] = d
    return mentions, first_seen


def build_backlog(*, memory_dir: Path, readme_path: Path,
                  project_root: Path, today: Optional[date] = None) -> tuple:
    if today is None:
        today = date.today()
    project_stages = _scan_project_stages(project_root)
    readme_stages = _scan_readme_stages(project_root)
    mentions, first_seen = _scan_memory_stages(memory_dir)
    mentioned = set(mentions.keys()) | readme_stages
    backlog_ids = sorted(mentioned - project_stages)
    bonus_ids = sorted(project_stages - mentioned)
    backlog: list = []
    for sid in backlog_ids:
        n = mentions.get(sid, 0)
        first = first_seen.get(sid, today)
        days = (today - first).days if n > 0 else 999
        # Avoid ZeroDivisionError; default 0.0 when no signal
        try:
            score = (n / (days + 1)) * 10 if n > 0 else 0.0
        except ZeroDivisionError:
            score = 0.0
        backlog.append(BacklogItem(
            id=sid, n_mentions=n,
            first_seen=first.isoformat() if n > 0 else "",
            days_since_first_seen=days,
            in_readme=sid in readme_stages,
            priority_score=score,
        ))
    backlog.sort(key=lambda b: -b.priority_score)
    return backlog, bonus_ids


def render_markdown(backlog: list, bonus: list,
                     n_in_code: int, n_in_mentioned: int) -> str:
    out: list[str] = ["# Stage Backlog", ""]
    out.append(f"*Generated by `src.analysis.stage_backlog` on "
                f"{time.strftime('%Y-%m-%d %H:%M:%S')}*\n")
    out.append("## Summary\n")
    out.append(f"- **Stages mentioned (memory or README)**: "
                f"{n_in_mentioned}")
    out.append(f"- **Stages in code (src/)**: {n_in_code}")
    out.append(f"- **Backlog (mentioned, not yet in code)**: "
                f"{len(backlog)}")
    out.append(f"- **Bonus (in code, not advertised)**: "
                f"{len(bonus)}")
    out.append("")
    out.append("## Backlog (priority order)\n")
    if backlog:
        out.append("| # | id | mentions | first_seen | days | score |")
        out.append("|---|---|---|---|---|---|")
        for i, b in enumerate(backlog, 1):
            out.append(f"| {i} | " + " | ".join(b.to_row()) + " |")
    else:
        out.append("*(empty - everything mentioned is in code)*\n")
    out.append("")
    if bonus:
        out.append("## Bonus (in code, not in memory/README)\n")
        out.append(f"- {', '.join(bonus)}")
        out.append("")
    return "\n".join(out)


def render_json(backlog: list, bonus: list) -> dict:
    return {
        "n_backlog": len(backlog),
        "n_bonus": len(bonus),
        "backlog": [asdict(b) for b in backlog],
        "bonus": bonus,
    }


def main() -> int:
    p = argparse.ArgumentParser(
        description="Stage backlog (promised-but-not-built)")
    p.add_argument("--memory_dir", type=Path,
                   default=Path("../.workbuddy/memory"))
    p.add_argument("--readme", type=Path, default=Path("README.md"))
    p.add_argument("--project_root", type=Path, default=Path("."))
    p.add_argument("--out", type=Path,
                   default=Path("report/stage_backlog.md"))
    p.add_argument("--out_json", type=Path,
                   default=Path("report/stage_backlog.json"))
    args = p.parse_args()
    project_stages = _scan_project_stages(args.project_root)
    readme_stages = _scan_readme_stages(args.project_root)
    mentions, _ = _scan_memory_stages(args.memory_dir)
    n_in_mentioned = len(set(mentions.keys()) | readme_stages)
    n_in_code = len(project_stages)
    backlog, bonus = build_backlog(
        memory_dir=args.memory_dir,
        readme_path=args.readme,
        project_root=args.project_root,
    )
    md = render_markdown(backlog, bonus, n_in_code=n_in_code,
                          n_in_mentioned=n_in_mentioned)
    print(f"[backlog] {len(backlog)} backlog items / "
          f"{len(bonus)} bonus; {n_in_mentioned} mentioned, "
          f"{n_in_code} in code")
    print(md)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(md, encoding="utf-8")
    print(f"Wrote Markdown -> {args.out}")
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(
        json.dumps(render_json(backlog, bonus), indent=2,
                    ensure_ascii=False),
        encoding="utf-8")
    print(f"Wrote JSON     -> {args.out_json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
